### ISSUE TITLE
Cannot create dyanmic model using ModelSchema

### ISSUE THREAD

**Issue by rishabhst** [rvinzent/django-dynamic-models#3] opened 2019-05-22 07:31 UTC
` File "/home/ubox72/Extras/graph/venv/lib/python3.6/site-packages/django/db/models/query.py", line 250, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/home/ubox72/Extras/graph/venv/lib/python3.6/site-packages/django/db/models/query.py", line 274, in __iter__
    self._fetch_all()
  File "/home/ubox72/Extras/graph/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1242, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/ubox72/Extras/graph/venv/lib/python3.6/site-packages/django/db/models/query.py", line 55, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/ubox72/Extras/graph/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1100, in execute_sql
    cursor.execute(sql, params)
  File "/home/ubox72/Extras/graph/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/ubox72/Extras/graph/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/ubox72/Extras/graph/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/ubox72/Extras/graph/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/ubox72/Extras/graph/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/ubox72/Extras/graph/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "dynamic_models_modelfieldschema" does not exist
LINE 1: ...ynamic_models_modelfieldschema"."max_length" FROM "dynamic_m...`
                                                             ^

**Comment by rvinzent** [comment] 2019-08-19 16:15
Closing as duplicate of #6. The issue there has a bit more discussion. Due to recent interest in this project, I will update the documentation soon with better setup instructions. Please feel free to re-open if you feel the issues have different root causes :)

**Closed by rvinzent** 2019-08-19 16:15 UTC
Labels: duplicate
